// NOTE: THIS IS AN AUTOGENERATED FILE.
export default [
  {
    name: "sfc",
    files: [
      "App.vue",
      "index.js",
      "pages/About.vue",
      "pages/Home.vue",
      "pages/Topics.vue",
      "pages/topics/Topic.vue"
    ],
    bundle: () => import("./sfc")
  },
  {
    name: "simple",
    files: ["index.js"],
    bundle: () => import("./simple")
  }
]
