// NOTE: THIS IS AN AUTOGENERATED FILE.
export default [
  {
    name: "active-links",
    files: [
      "About.vue",
      "App.vue",
      "Home.vue",
      "index.js",
      "User.vue",
      "Users.vue"
    ],
    bundle: () => import("./active-links")
  },
  {
    name: "auth-flow",
    files: [
      "auth.js",
      "components/About.vue",
      "components/App.vue",
      "components/Dashboard.vue",
      "components/Login.vue",
      "index.js"
    ],
    bundle: () => import("./auth-flow")
  },
  {
    name: "basic",
    files: ["index.js"],
    bundle: () => import("./basic")
  },
  {
    name: "data-fetching",
    files: ["api.js", "index.js", "Post.vue"],
    bundle: () => import("./data-fetching")
  },
  {
    name: "lazy-loading",
    files: ["Bar.vue", "Baz.vue", "Foo.vue", "index.js"],
    bundle: () => import("./lazy-loading")
  },
  {
    name: "named-routes",
    files: ["index.js"],
    bundle: () => import("./named-routes")
  },
  {
    name: "named-views",
    files: ["index.js"],
    bundle: () => import("./named-views")
  },
  {
    name: "navigation-guards",
    files: ["index.js"],
    bundle: () => import("./navigation-guards")
  },
  {
    name: "nested-router",
    files: ["index.js"],
    bundle: () => import("./nested-router")
  },
  {
    name: "nested-routes",
    files: ["index.js"],
    bundle: () => import("./nested-routes")
  },
  {
    name: "redirect",
    files: ["index.js"],
    bundle: () => import("./redirect")
  },
  {
    name: "route-alias",
    files: ["index.js"],
    bundle: () => import("./route-alias")
  },
  {
    name: "route-matching",
    files: ["index.js"],
    bundle: () => import("./route-matching")
  },
  {
    name: "route-props",
    files: ["Hello.vue", "index.js"],
    bundle: () => import("./route-props")
  },
  {
    name: "scroll-behavior",
    files: ["index.js"],
    bundle: () => import("./scroll-behavior")
  },
  {
    name: "sfc",
    files: [
      "App.vue",
      "index.js",
      "pages/About.vue",
      "pages/Home.vue",
      "pages/Topics.vue",
      "pages/topics/Topic.vue"
    ],
    bundle: () => import("./sfc")
  },
  {
    name: "simple",
    files: ["index.js"],
    bundle: () => import("./simple")
  },
  {
    name: "transitions",
    files: ["index.js"],
    bundle: () => import("./transitions")
  }
]
